pipeline {
    agent none
    
    environment {
        DOCKER_ID = credentials('DOCKER_ID')
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
    }

    stages {
        stage('Build and test the backend') {
            agent {
                    docker {
	                    image "maven:3-eclipse-temurin-20"
                        args "-u root"
 		            }
            }
            stages {
                stage('Build') {
                    steps {
                        dir("backend") {
                            echo 'Compiling...'
                            sh 'mvn clean install -DskipTests -Dcheckstyle.skip'
                        }
                    }
                }
                stage('Test') {
                    steps {
                        dir("backend") {
                            echo 'Testing...'
                            sh 'mvn verify -Dcheckstyle.skip'     
                        }
                    }
                }
                stage('Checkstyle ') {
                    steps {
                        dir("backend") {
                            echo 'Checkstyle...'
                            sh 'mvn checkstyle:check'
                        }
                    }
                }
                stage('Package') {
                    steps {
                        dir("backend") {
                            echo 'Packaging...'
                            sh 'mvn package -DskipTests -Dcheckstyle.skip'
                        }
                    }
                }
            }
            post { 
                always {
                    dir("backend") {
                        sh 'mvn clean'
                    }
                }
            }
        }
        stage('Build and publish docker image of backend') {
            agent any
            stages {
                stage('Init') {
                    steps {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin'
                        sh '(docker context inspect mybuilder && docker context use mybuilder) || docker context create mybuilder'
			            //sh '(docker buildx inspect mybuilder && docker buildx use mybuilder) || docker buildx create --name mybuilder --use --bootstrap'
                    }
                }
                stage('Build') {
                    steps {
                        sh 'docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $DOCKER_ID/ytsms-backend:latest -f backend/deployment/Dockerfile .'
                    }
                }
                stage('Publish') {
                    steps {
                        echo 'Published stub'
                    }
                }
            }
            post { 
                always {
                    sh 'docker images -q | xargs --no-run-if-empty docker rmi'
                    sh 'docker logout'
                    sh 'docker context rm mybuilder'
                    sh 'docker buildx rm mybuilder'
                }
            }
        }
    }
}
