pipeline {
    agent none
    
    environment {
        DOCKER_ID = credentials('DOCKER_ID')
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
        BUILDER_NAME = 'mbuilder'
        SERVICE = 'ytsms'
    }

    stages {
        stage('Build and test the backend') {
            agent {
                    docker {
	                    image "maven:3-eclipse-temurin-20"
                        args "-u root"
 		            }
            }
            stages {
                stage('Build') {
                    steps {
                        dir("backend") {
                            echo 'Compiling...'
                            sh 'mvn clean install -DskipTests -Dcheckstyle.skip'
                        }
                    }
                }
                stage('Test') {
                    steps {
                        dir("backend") {
                            echo 'Testing...'
                            sh 'mvn verify -Dcheckstyle.skip'     
                        }
                    }
                }
                stage('Checkstyle ') {
                    steps {
                        dir("backend") {
                            echo 'Checkstyle...'
                            sh 'mvn checkstyle:check'
                        }
                    }
                }
                stage('Package') {
                    steps {
                        dir("backend") {
                            echo 'Packaging...'
                            sh 'mvn package -DskipTests -Dcheckstyle.skip'
                            echo 'Stash files'
                            sh 'ls target/'
                            stash includes: 'target/*.jar', name: 'jarFiles'
                        }
                    }
                }
            }
            post {
                always {
                    dir("backend") {
                        sh 'mvn clean'
                    }
                }
            }
        }
        stage('Build and publish docker image of backend') {
            agent any
            stages {
                stage('Login') {
                    steps {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin'
                    }
                }
                stage("Create Buildx Builder") {
                    steps {
                        sh """
                        docker context create $BUILDER_NAME
                        docker context use $BUILDER_NAME
                        docker buildx create --use $BUILDER_NAME
                        """
                    }
                }
                stage("Build multi-arch image") {
                    steps {
                        dir("backend") {
                            unstash 'jarFiles'
                            sh """
                                docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_ID/$SERVICE-backend:latest -f deployment/Dockerfile .
                            """
                        }
                    }
                }
                stage('Publish') {
                    steps {
                        echo 'Published stub'
                    }
                }
            }
            post { 
                always {
                    sh """
                        docker stop \$(docker ps -a -q)
                        docker images -q | xargs --no-run-if-empty docker rmi -f
                        docker buildx use default
                        docker context rm $BUILDER_NAME
                    """
                }
            }
        }
    }
}
